[package]
name = "silver-octo-winner"
version = "0.1.0"
authors = ["Red Carpet"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
#![feature(proc_macro_hygiene)]

[dependencies]
rocket = "0.4.2"
